### ISSUE TITLE
Should an OrActivityContext be a set, bag, or list ? A.k.a. is equals correct?

### ISSUE THREAD

**Issue by jmaassen** [NLeSC/Constellation#8]
In the current implementation, the `OrActivityContext` behaves either like a bag or a list, depending on the value of the `ordered` parameter of the constructor. If `ordered` is `true` the order matters and the context is a list, if it is `false` it does not matter and the order is a bag. 

The implementation of `equals` however seems to test for set equality in the worst case (slow path) implementation, but behaves differently in the fast path implementation. This is hard to trigger in a test, as several fast paths guarantee that this slow path is almost never reached.
 
One issue is the comparison in the occurrence of doubles values. In other words:

     (A, B) == (A, B, B) ?

The current implementation says no since their length is different. Are these the semantics we want ? 

Similar problems occur with comparing ordered and not ordered, or does: 

   (B, A)[with order] == (A, B)[without order]

Again, the fast path in equals says no (by comparing their hash codes), the slow path says yes by testing set equality. Again, are these the semantics we want ?

**Comment by CerielJacobs** [comment]
Looks like "unfinished". Looking at it now, I think that "ordered" should be part of the context. Also, testing for set equality should be avoided at all times, and we can, because on unordered contexts the elements are sorted. I think a context that is explicitly ordered should not compare equal to a context that happens to have its members in the same order.
Is there any reason to allow duplicate entries? If not, we should remove duplicates. Of course, we should also test for null pointers.

**Comment by jmaassen** [comment]
Agreed. I already added the `null` check to the constructor in the unittest branch. I'll also fix the equals.

One downside of checking duplicates it that it is potentially expensive to do?

**Comment by CerielJacobs** [comment]
I cannot think of any reason to allow duplicates, but maybe in "ordered" we should keep them. After all, that's what the user said. In unordered, we sort anyway, so after that removing duplicates should not be too expensive.

**Comment by jmaassen** [comment]
OK, will implement that.

**Comment by jmaassen** [comment]
Fixed in 55b1445228cc9c66d649d0cc5e1335247a653d1e
